#!/bin/python3

#build dir
# cp -r defpack tpacks


# # Environs
# export PACK_INFO_REQ="https://127.0.0.1:3017/packs"

# # Params
# BUTLER_PORT=3017
# FRONT_PORT=8080

# echo "Running butler server"
# cd butler && python3 server.py $BUTLER_PORT & disown
# echo -e "\n\n\n\n\n\n"

# echo "Running frontend server"
# cd front && python3 server.py $FRONT_PORT & disown
# echo -e "\n\n\n\n\n\n"


import asyncio
import sys
import subprocess
import time
import os


# Environs
os.environ["DEF_PROD_SERVER"]="https://127.0.0.1:3017"

# Params
BUTLER_PORT=3017
FRONT_PORT=8080


async def run_prod():
    global prod_serv
    # Create the subprocess; redirect stdout to a pipe
    prod_serv = await asyncio.create_subprocess_shell(
        f"cd prod_server && python3 server.py {BUTLER_PORT}",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE, env=os.environ)
    
    # l, e = await butler_serv.communicate()
    # print(l, e)
    
async def run_front():
    global front_serv
    # Create the subprocess; redirect stdout to a pipe
    front_serv = await asyncio.create_subprocess_shell(
        f"cd front && python3 server.py {FRONT_PORT}",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE, env=os.environ)
    
    # l, e = await front_serv.communicate()
    # print(l, e)
    

if __name__ == "__main__":

    print("Moving default packs")
    os.system("mkdir tpacks")
    os.system("cp -vr defpacks/* tpacks")
    #subprocess.call(["cp", "-r", "defpack", "tpacks"])
    
    print("Compiling cmpf")
    os.system("cd prod_server/compiler && ./build.sh")

    print("Installing pympofl")
    os.system("cd pympofl && ./install.sh")
    

    print("Compilation finished")
    if ("+run" in sys.argv):
        print("Turn 1")

        asyncio.run(run_prod())
        print("started prod_server")
        time.sleep(1)
        asyncio.run(run_front())
        print("started front")
        while 1: 
            pass